groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path("", views.ListGroupView.as_view(), name="all"),
    path("new/", views.CreateGroupView.as_view(), name="create"),
    path("posts/in/<slug:slug",views.SingleGroupView.as_view(), name="single"),
    path("join/", views.JoinGroup.as_view(), name='join'),
    path("leave/", views.LeaveGroup.as_view(), name="leave")
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.PostListView.as_view(), name="all"),
    path("new/", views.CreatePostView.as_view(), name="create"),
    path("by/<str:username>", views.UserPostsView.as_view(), name="for_user"),
    path("by/<str:username>/<int:pk>", views.PostDetailView.as_view(), name="single"),
    path("delete/<int:pk>", views.DeletePostView.as_view(), name="delete"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("posts/", include("posts.urls")),
    path("groups/", include("groups.urls")),
]

groups/models.py
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
User = get_user_model()
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default="")
    description_html = models.TextField(editable=True, default="", blank=True)
    members = models.ManyToManyField(User, through="GroupMember")

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse("groups:single", kwargs={'slug':self.slug})
    
    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memeberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="user_group", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.contrib import messages
from django.views import generic
from .models import Group, GroupMember

class CreateGroupView(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroupView(generic.DetailView):
    model = Group

class ListGroupView(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self):
        return reverse("groups:single", kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,"Warning, already a member")
        else:
            messages.success(self.request, "You are now a member")
        
        return super().get(request, *args, **kwargs)
    
class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            )
        except GroupMember.DoesNotExist:
            messages.warning(self.request,"Sorry you are not in this group")
        else:
            membership.delete()
            messages.success(self.request, "You've left the group")
        return super().get(request,*args,**kwargs)
            
    

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% block pregroup %} {% endblock pregroup %}
        {% block post_content %} {% endblock post_content %}
        {% block postgroup %} {% endblock postgroup %}
    </div>
</div>
{% endblock content %}

groups/templates/groups/group_detial.html
{% extends "group_base.html" %}
{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>
<div class="content">
    {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
        <span class="glyphicon glyphicon-remove-circle">Leave</span></a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-default">
        <span class="glyphicon glyphicon-ok-circle">Join</span></a>
    {% endif %}
</div>
{% endblock pregroup %}
{% block post_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %}
    <h2>This group has no posts.</h2>
    {% else %}
    {% for post in group.posts.all %}
    {% include "posts/_post.html" %}
    {% endfor %}
    {% endif %}
</div>
{% endblock post_content %}
{% block postgroup %} {% endblock postgroup %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load crispy_forms_tags %}
{% block pregroup %}
<h4>Create a new group!</h4>
<form action="{% url 'groups:create' %}" method="post" id="groupForm">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn btn-primary btn-large" value="Create">
</form>
{% endblock pregroup %}
{% block post_content %} {% endblock post_content %}
{% block postgroup %} {% endblock postgroup %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-8">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>
            Welcome Back
            <a href="{%url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
        </h2>

        {% endif %}
        <h2>Groups</h2>

        <p>Welcome to the groups page! Select a group</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign"></span>Create New Group</a>
    {% endif %}
</div>
{% endblock pregroup %}

{% block post_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">{{group.description_html|safe}}</div>
            <div class="row">
                <div class="col-md-4">
                    <span class="badge">{{group.members.count}}</span> member{{group.members.count|pluralize}}
                </div>
                <div class="col-md-4">
                    <span class="badge">{{group.posts.count}}</span> post{{group.posts.count|pluralize}}
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock post_content %}
{% block postgroup %} {% endblock postgroup %}